/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-01-10 23:40:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewSignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7; IE=EmulateIE9\">\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style1.css\" media=\"all\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"demo.css\" media=\"all\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("\t\t\t<!-- freshdesignweb top bar -->\n");
      out.write("            <div class=\"freshdesignweb-top\">\n");
      out.write("                <a href=\"http://www.freshdesignweb.com\" target=\"_blank\">Home</a>\n");
      out.write("                <span class=\"right\">\n");
      out.write("                    <a href=\"http://www.freshdesignweb.com/beautiful-registration-form-with-html5-and-css3.html\">\n");
      out.write("                        <strong>Back to the freshdesignweb Article</strong>\n");
      out.write("                    </a>\n");
      out.write("                </span>\n");
      out.write("                <div class=\"clr\"></div>\n");
      out.write("            </div><!--/ freshdesignweb top bar -->\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\t<h1><span>Tutorials</span> Demo Beautiful Registration Form with HTML5 and CSS3</h1>\n");
      out.write("            </header>       \n");
      out.write("      <div  class=\"form\">\n");
      out.write("    \t\t<form id=\"contactform\"> \n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"name\">Name</label></p> \n");
      out.write("    \t\t\t<input id=\"name\" name=\"name\" placeholder=\"First name\" required=\"\" tabindex=\"1\" type=\"text\"> \n");
      out.write("    \t\t\t <input id=\"name\" name=\"name\" placeholder=\"Last name\" required=\"\" tabindex=\"1\" type=\"text\">\n");
      out.write("    \t\t\t \n");
      out.write("    \t\t\t <p class=\"contact\"><label for=\"phone\">Mobile phone</label></p> \n");
      out.write("            <input id=\"phone\" name=\"phone\" placeholder=\"phone number\" required=\"\" tabindex=\"2\" type=\"text\">\n");
      out.write("            \n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"email\">Email</label></p> \n");
      out.write("    \t\t\t<input id=\"email\" name=\"email\" placeholder=\"example@domain.com\" required=\"\"  tabindex=\"3\" type=\"text\"> \n");
      out.write("    \t\t\t\n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"street\">Street Address</label></p> \n");
      out.write("    \t\t\t<input id=\"street\" name=\"street\" placeholder=\"777 Lucky Street\" required=\"\" tabindex=\"4\" type=\"text\">\n");
      out.write("    \t\t\t\n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"city\">City</label></p>\n");
      out.write("    \t\t\t<input type=\"text\" id=\"city\" name=\"city\" placeholder=\"Kansas City\" required=\"\" tabindex=\"5\">\n");
      out.write("    \t\t\t\n");
      out.write("    \t\t\t<p class=\"contact\"><label for=\"state\">State</label></p>\n");
      out.write("   \t\t\t <input type=\"text\" id=\"state\" name=\"state\" placeholder=\"MO\" required=\"\" tabindex=\"6\">\n");
      out.write("   \t\t\t \n");
      out.write("   \t\t\t<p class=\"contact\"><label for=\"zipCode\">Zip Code</label></p>\n");
      out.write("   \t\t\t <input type=\"text\" id=\"zipCode\" name=\"zipCode\" placeholder=\"63098\" required=\"\" tabindex=\"7\">\n");
      out.write("                \n");
      out.write("                <p class=\"contact\"><label for=\"username\">Create a username</label></p> \n");
      out.write("    \t\t\t<input id=\"username\" name=\"username\" placeholder=\"username\" required=\"\" tabindex=\"8\" type=\"text\"> \n");
      out.write("    \t\t\t \n");
      out.write("                <p class=\"contact\"><label for=\"password\">Create a password</label></p> \n");
      out.write("    \t\t\t<input type=\"password\" id=\"password\" name=\"password\" required=\"\"> \n");
      out.write("                <p class=\"contact\"><label for=\"repassword\">Confirm your password</label></p> \n");
      out.write("    \t\t\t<input type=\"password\" id=\"repassword\" name=\"repassword\" required=\"\"> \n");
      out.write("        \n");
      out.write("               <fieldset>\n");
      out.write("                 <label>Birthday</label>\n");
      out.write("                  <label class=\"month\"> \n");
      out.write("                  <select class=\"select-style\" name=\"BirthMonth\">\n");
      out.write("                  <option value=\"\">Month</option>\n");
      out.write("                  <option  value=\"01\">January</option>\n");
      out.write("                  <option value=\"02\">February</option>\n");
      out.write("                  <option value=\"03\" >March</option>\n");
      out.write("                  <option value=\"04\">April</option>\n");
      out.write("                  <option value=\"05\">May</option>\n");
      out.write("                  <option value=\"06\">June</option>\n");
      out.write("                  <option value=\"07\">July</option>\n");
      out.write("                  <option value=\"08\">August</option>\n");
      out.write("                  <option value=\"09\">September</option>\n");
      out.write("                  <option value=\"10\">October</option>\n");
      out.write("                  <option value=\"11\">November</option>\n");
      out.write("                  <option value=\"12\" >December</option>\n");
      out.write("                  </label>\n");
      out.write("                 </select>    \n");
      out.write("                <label>Day<input class=\"birthday\" maxlength=\"2\" name=\"BirthDay\"  placeholder=\"Day\" required=\"\"></label>\n");
      out.write("                <label>Year <input class=\"birthyear\" maxlength=\"4\" name=\"BirthYear\" placeholder=\"Year\" required=\"\"></label>\n");
      out.write("              </fieldset>\n");
      out.write("  \n");
      out.write(" \t\t <p class=\"contact\"><label for=\"accountName\">Name this account</label></p>\n");
      out.write("   \t\t <input type=\"text\"  id=\"accountName\" name=\"accountName\" placeholder=\"Ex: Joe's Checking\">\n");
      out.write("   \t\t \n");
      out.write("   \t\t  <p class=\"contact\"><label for=\"balance\">Enter Starting Balance</label></p>\n");
      out.write("   \t\t  <input type=\"double\"  id=\"balance\" name=\"balance\" placeholder=\"min. 5.00\">\n");
      out.write("            \n");
      out.write("             <br>\n");
      out.write("            <input class=\"buttom\" name=\"submit\" id=\"submit\" tabindex=\"9\" value=\"Sign me up!\" type=\"submit\"> \t \n");
      out.write("   </form> \n");
      out.write("</div>      \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
