/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-01-08 23:03:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Join the Greatest Bank Ever</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./styles/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\" integrity=\"sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("<body class=\"mybody\">\n");
      out.write("<div class=\"jumbotron\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t <h1> Lets get you signed up</h1>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("<form action=\"AccountServlet\" method=\"post\">\n");
      out.write("<div class=\"form-row\">\n");
      out.write("<div class=\"form-group col-md-4\">\n");
      out.write("    <label for=\"firstName\">First Name</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" placeholder=\"John\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group col-md-4\">\n");
      out.write("    <label for=\"lastName\">Last Name</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" placeholder=\"Doe\">\n");
      out.write("  </div> </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"telephone\">Telephone Number</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"telephone\" name=\"telephone\" placeholder=\"ex:3146347744\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-row\">\n");
      out.write("  <div class=\"form-group col-md-4\">\n");
      out.write("    <label for=\"street\">Street</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"street\" name=\"street\" placeholder=\"777 Lucky Street\"> \n");
      out.write("  </div><div class=\"form-group col-md-4\">\n");
      out.write("    <label for=\"city\">City</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"city\" name=\"city\" placeholder=\"Kansas City\">\n");
      out.write("  </div><div class=\"form-group col-md-1\">\n");
      out.write("    <label for=\"state\">State</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"state\" name=\"state\" placeholder=\"MO\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group col-md-1\">\n");
      out.write("    <label for=\"zipCode\">Zip Code</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"zipCode\" name=\"zipCode\" placeholder=\"63098\">\n");
      out.write("  </div></div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label for=\"email\">Email Address</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"JohnDoe@gmail.com\">\n");
      out.write("  </div><div class=\"form-row\">\n");
      out.write("  <div class=\"form-group col-md-6\">\n");
      out.write("    <label for=\"userName\">Username</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"userName\" name=\"userName\" placeholder=\"JDoe47\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group col-md-6\">\n");
      out.write("    <label for=\"password\">Password</label>\n");
      out.write("    <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"******\">\n");
      out.write("  </div></div>\n");
      out.write("  <div class=\"form-group col-md-6\">\n");
      out.write("    <label for=\"accountName\">Name this account</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"accountName\" name=\"accountName\" placeholder=\"Ex: Joe's Checking\">\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group col-md-2\">\n");
      out.write("    <label for=\"balance\">Enter Starting Balance</label>\n");
      out.write("    <input type=\"double\" class=\"form-control\" id=\"balance\" name=\"balance\" placeholder=\"min. 5.00\">\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary\">Sign me up</button>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
